config/routes.rb
Rails.application.routes.draw do
  root 'used_cars#index'
  get 'used_cars' => 'used_cars#index'
  get 'used_cars/new' => 'used_cars#new'
  get 'used_cars/:id' => 'used_cars#show', as: :album
  post 'used_cars' => 'used_cars#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup'  => 'users#new'
  resources :users

end

app/models/used_car.rb
class UsedCar < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

skip_before_action :verify_authenticity_token

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/used_cars'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/used_cars_controller.rb
class UsedCarsController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
    @used_cars = UsedCar.all
  end

  def show
    @used_car = UsedCar.find(params[:id])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <div class="header">
    <div class="container">

      <div class="nav pull-right">
        <% if current_user %>
          <ul>
            <li><%= current_user.email %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        <% else %>
          <ul>
            <li><%= link_to "Login", 'login' %></a></li>
            <li><%= link_to "Signup", 'signup' %></a></li>
          </ul>
         <% end %>
      </div>
    </div>
  </div>

      <%= yield %>

  </body>
</html>

app/views/used_cars/index.html.erb
<h1>Listing Used Cars</h1>

<table>
  <tr>
    <th>Used Cars</th>
    <th>List</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @used_cars.each do |used_car| %>
  <tr>
    <td><%= used_car.title %></td>
    <td><%= used_car.content %></td>
    <td><%= link_to "Show", used_car %></td>
    <td><%= link_to "Edit", edit_used_car_path(used_car) %></td>
    <td><%= link_to "Remove", used_car, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to "New used_car", new_used_car_path %>

app/views/used_cars/show.html.erb
<h1>Used car show</h1>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>


    </div>
  </div>
</div>